model:
  path: 'bestmodels/doubleloss_best_val2_100e/best.onnx'

robot:
  max_speed: 0.15
  max_steering: 0.55
  differential: #TODO to jesli na wprost nie jedzie prosto ig
    left: 1.0
    right: 1.0